language: node_js
node_js:
 - "8"
before_install:
 - cd client
install:
 - npm install
 - cd client
 - npm install
 - cd ..
script:
 - npm start &
 - cd client
 - npm start
 - npm run eslint 
 - npm run jsdoc
 - npm test
 - npm run build
after_script:
 - cd ..
